### PR TITLE
Add labels documentation

### PR DESCRIPTION
**Pull request by thaJeztah**
Adds more documentation for labels and adds the label instruction to the man-pages.

Also included is a document called "Labels - custom meta-data in Docker" in the user-guide,
this is still a work-in-progress I started to describe the "namespaces" conventions, an example on
storing structured data.

I ran a bit "out of steam" (writers block?) on that document, but kept it in (for now), in case
it still ends up useful.

The Remote API documentation changes will need to be moved to the docker_remote_api_v1.18.md document when rebasing the whole PR.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@ibuildthecloud decided to (finally) create a PR. It's still a working-draft (as explained above), but work is quite busy at the moment for me, so many times I couldn't get myself motivated enough to come up with something better.

I thought it'd be better to (at least) give you something to work on, and if I have something better, I can add a follow-up.

Apologies for taking so long on this, but I hope it's useful.

**Comment by thaJeztah** [comment]
Oops, looks like I forgot to push one change, will update in a minute

**Comment by ibuildthecloud** [comment]
@thaJeztah So sorry, I didn't see this.  I've been heads down working on something really exciting that will be released tomorrow.  I'll get back to the labels PR on weds hopefully.  Thanks so much for your help.

**Comment by thaJeztah** [comment]
@ibuildthecloud no problem! Work goes first, right? Looking forward to the announcement.

I hope rebasing isn't too problematic for your labels PR, and will keep thinking if I can come up with better descriptive docs, just ran into a bit of a "writers block" (probably just too busy at work to still have inspiration).

Keep me posted, thanks a lot for your effort!

**Comment by ibuildthecloud** [comment]
I just cherry picked this commit and added it to the branch I rebased.  Sorry if I prematurely pushed it, but just wanted to get as much out there since I've gotten the attention of the core maintainers.

**Comment by thaJeztah** [comment]
:+1: wise choice.  :)

**Pull request closed without merging**
